<?php $clickheatConf = array (
  'logPath' => '/data/projects/clickheat/logs/',
  'cachePath' => '/data/projects/clickheat/cache/',
  'referers' =>
  array (
    0 => 'www.dugwood.com',
    1 => 'www.dugwood.fr',
    2 => 'projects.dugwood.com',
  ),
  'groups' =>
  array (
    0 => 'clickheat',
    1 => 'index',
  ),
  'filesize' => 0,
  'adminLogin' => 'admin',
  'adminPass' => '9e237a71b3361dcb8c120833760bc42e',
  'viewerLogin' => 'demo',
  'viewerPass' => 'fe01ce2a7fbac8fafaed7c982a04e229',
  'memory' => 50,
  'step' => 5,
  'dot' => 19,
  'flush' => 40,
  'start' => 'm',
  'palette' => false,
  'heatmap' => true,
  'hideIframes' => true,
  'hideFlashes' => true,
  'yesterday' => false,
  'alpha' => 80,
  'version' => '1.14',
  '__screenSizes' =>
  array (
    0 => 0,
    1 => 240,
    2 => 640,
    3 => 800,
    4 => 1024,
    5 => 1152,
    6 => 1280,
    7 => 1440,
    8 => 1600,
    9 => 1800,
  ),
  '__browsersList' =>
  array (
    'all' => '',
    'msie' => 'Internet Explorer',
    'firefox' => 'Firefox',
    'chrome' => 'Chrome',
    'safari' => 'Safari',
    'opera' => 'Opera',
    'unknown' => '',
  ),
);